import { MasterAnswer } from "./interviewHelpers";

/**
 * Banco Maestro Mercado Libre — NoSQL Service Team
 * Alineado a la JD: Sr Software Engineer - NoSQL Service Team (ID 126318)
 * y a la evaluación técnica automatizada con Valeria (Agente de IA en Eightfold.ai)
 * y paneles técnicos de arquitectura distribuida de Mercado Libre.
 *
 * Directivas estrictas:
 * - Cumplimiento del Zero-Bullet Mandate: exactamente 2 oraciones concisas y directas sin viñetas.
 * - Discriminar +8 años IT total vs ~4 años Cloud/GCP/Kubernetes.
 * - Anclado 100% al CV real de Guillermo Fernando Farfán Romero (Salta, Argentina).
 */
export const MELI_NOSQL_MASTER_ANSWERS: MasterAnswer[] = [
  // ══════════════════════════════════════════════════════════
  // SECCIÓN 1: SCREENING, PERFIL & VALERIA (EIGHTFOLD AI)
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_tell_me_about_yourself",
    question: "Tell me about yourself or walk me through your background and experience.",
    enText: "I'm Fernando, a Software and Cloud Infrastructure Engineer with eight years in software systems and four years dedicated to cloud platforms. I specialize in high-throughput data architectures, connection pooling, and automated Kubernetes platforms tailored for low-latency Latin American scale.",
    esText: "Soy Fernando, Ingeniero de Software e Infraestructura Cloud con ocho años en sistemas de software y cuatro años dedicados a plataformas cloud. Me especializo en arquitecturas de datos de alto throughput, pooling de conexiones y plataformas Kubernetes de baja latencia a escala regional.",
    category: "Screening",
    tags: ["presentation", "background", "about me", "introduction", "cv", "trayectoria"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_experience_strict",
    question: "¿Cuántos años de experiencia tienes en ingeniería de software y arquitecturas en la nube?",
    enText: "I bring over eight years of total software engineering experience alongside four years focused specifically on cloud infrastructure, Kubernetes, and database reliability. This dual foundation allows me to build resilient distributed services with deep platform and systems understanding.",
    esText: "Cuento con más de ocho años de experiencia total en ingeniería de software y cuatro años enfocados específicamente en infraestructura cloud, Kubernetes y confiabilidad de bases de datos. Este balance me permite construir servicios distribuidos resilientes con sólido dominio de sistemas.",
    category: "Screening",
    tags: ["experience", "years", "años", "seniority"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_why_nosql_team",
    question: "¿Por qué elegiste postularte específicamente al NoSQL Service Team de Mercado Libre?",
    enText: "The NoSQL Service Team operates at the very foundation of Mercado Libre's ecosystem, supporting millions of transactions with strict low-latency requirements. Building multi-cloud database abstractions and proxy routing at this scale represents the exact systems engineering challenge where my experience creates immediate value.",
    esText: "El NoSQL Service Team opera en el corazón de la plataforma de Mercado Libre, respaldando millones de transacciones con exigencias críticas de baja latencia. Diseñar abstracciones multi-cloud y ruteo de proxies a esta escala representa el desafío de ingeniería de sistemas donde mi experiencia aporta valor inmediato.",
    category: "Screening",
    tags: ["motivation", "why meli", "nosql team", "impact", "systems"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_salary_expectation",
    question: "¿Cuáles son tus pretensiones salariales para este rol de Senior Software Engineer?",
    enText: "My reference compensation is four thousand US dollars per month gross, open to exploring Mercado Libre's competitive local or regional senior compensation structure. My main priority is aligning with the scope, ownership, and technical impact of the NoSQL Service Team.",
    esText: "Mi remuneración de referencia ronda los cuatro mil dólares mensuales brutos, estando totalmente abierto a la estructura salarial competitiva de Mercado Libre para este nivel senior. Mi prioridad principal es el impacto técnico y los desafíos del equipo de NoSQL.",
    category: "Screening",
    tags: ["salary", "remuneración", "expectativa", "compensación"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_remote_work_salta",
    question: "¿Cómo gestionas el trabajo en equipo distribuido y la comunicación asíncrona de manera remota?",
    enText: "I work remotely from Salta, Argentina, relying on structured Architecture Decision Records, clear pull request documentation, and proactive asynchronous communication. This self-driven discipline ensures high alignment across regional time zones without creating meeting bottlenecks.",
    esText: "Trabajo en remoto desde Salta, apoyándome en Architecture Decision Records estructurados, pull requests bien documentados y comunicación asíncrona proactiva. Esta disciplina autónoma asegura alineación técnica entre zonas horarias sin generar cuellos de botella en reuniones.",
    category: "Screening",
    tags: ["remote", "salta", "asynchronous", "communication", "autonomy", "adrs"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_casual_dog_luna",
    question: "¿Qué haces en tu tiempo libre o qué te gusta fuera de la ingeniería?",
    enText: "When I'm not architecting systems, I enjoy outdoor activities and spending time with my rescued dog Luna here in Salta. Taking long walks in the hills keeps me grounded and brings great clarity for solving complex distributed systems problems.",
    esText: "Cuando no estoy diseñando sistemas, disfruto de actividades al aire libre y compartir tiempo con mi perrita rescatada Luna acá en Salta. Salir a caminar por los cerros me desconecta y me da gran claridad mental para resolver problemas complejos de arquitectura.",
    category: "Screening",
    tags: ["casual", "icebreaker", "hobbies", "luna", "salta"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 2: CULTURA MERCADO LIBRE & PRINCIPIOS
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_culture_fit",
    question: "¿Por qué te interesa sumarte a Mercado Libre y cómo te identificas con principios como Beta Continuo?",
    enText: "Mercado Libre's culture of continuous beta and calculated risk-taking perfectly matches how I build software: shipping high-velocity iterations with feature toggles, automated rollbacks, and proactive telemetry. I thrive in environments where engineering teams take genuine ownership of their platforms and compete collaboratively to create real economic impact across Latin America.",
    esText: "La cultura de Beta Continuo y emprender tomando riesgos de Mercado Libre coincide plenamente con mi forma de trabajar: iterar rápido con feature toggles, rollbacks automatizados y telemetría proactiva. Me motiva trabajar en equipos donde los ingenieros asumimos verdadero ownership de nuestras plataformas y competimos en equipo para generar impacto real en millones de personas en América Latina.",
    category: "Behavioral",
    tags: ["culture", "beta continuo", "mercadolibre", "ownership", "valores"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_culture_calculated_risk",
    question: "¿Cómo aplicas el principio de 'Emprender tomando riesgos' al diseñar sistemas críticos de datos?",
    enText: "I take calculated risks by introducing controlled architectural spikes backed by automated shadow traffic and automated canary rollouts. Decoupling deployment from activation allows rapid innovation while ensuring a zero blast radius if unexpected bottlenecks emerge.",
    esText: "Tomo riesgos calculados ejecutando spikes arquitectónicos controlados respaldados por shadow traffic y rollouts canary automatizados. Desacoplar el despliegue de la activación permite innovar a gran velocidad asegurando un radio de explosión nulo si surgen cuellos de botella inesperados.",
    category: "Behavioral",
    tags: ["culture", "riesgo", "spikes", "canary", "shadow traffic"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_culture_execution_excellence",
    question: "¿Qué significa para ti 'Ejecutar con excelencia' en una plataforma de infraestructura compartida?",
    enText: "Executing with excellence means treating platform resilience, comprehensive automated testing, and clear client documentation as non-negotiable first-class deliverables. Ensuring that downstream microservices experience zero downtime and predictable sub-twenty millisecond latencies demonstrates true engineering craftsmanship.",
    esText: "Ejecutar con excelencia implica considerar la resiliencia de plataforma, los tests automatizados y la documentación clara para clientes como entregables de primer nivel no negociables. Garantizar que los microservicios aguas abajo experimenten cero downtime y latencias predecibles bajo veinte milisegundos refleja verdadero profesionalismo técnico.",
    category: "Behavioral",
    tags: ["culture", "excelencia", "craftsmanship", "resiliencia", "calidad"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 3: MULTI-CLOUD NOSQL & STORAGE ENGINES
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_multicloud_nosql",
    question: "¿Cómo evaluarías e implementarías soporte multi-nube para bases de datos NoSQL más allá de AWS DocumentDB, considerando alternativas como GCP Firestore o MongoDB?",
    enText: "I evaluate consistency semantics, read and write latency profiles, protocol compatibility, and operational cost across cloud vendors. Building a database proxy abstraction layer normalizes query primitives and telemetry between DocumentDB and Firestore without mutating client contracts.",
    esText: "Evalúo semántica de consistencia, perfiles de latencia en lectura y escritura, compatibilidad de protocolos y costos operativos entre proveedores cloud. Construir una capa de proxy de base de datos desacopla las primitivas de consulta y normaliza la telemetría sin modificar contratos de clientes.",
    category: "Technical",
    tags: ["nosql", "multicloud", "documentdb", "firestore", "mongodb", "aws", "gcp", "database"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_documentdb_vs_firestore_internals",
    question: "¿Cuáles son las diferencias arquitectónicas clave entre AWS DocumentDB y GCP Firestore a bajo nivel?",
    enText: "DocumentDB decouples compute from an emulated distributed log storage layer across three availability zones using MongoDB wire-protocol compatibility. In contrast, Firestore utilizes multi-region Paxos consensus over Bigtable storage with native serverless autoscaling and real-time document change listeners.",
    esText: "DocumentDB desacopla cómputo de una capa de log de almacenamiento distribuido en tres zonas con compatibilidad del protocolo de MongoDB. En cambio, Firestore utiliza consenso Paxos multi-región sobre almacenamiento Bigtable con autoescalado serverless y listeners de cambios en tiempo real.",
    category: "Technical",
    tags: ["documentdb", "firestore", "internals", "architecture", "aws", "gcp", "storage engine"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_when_to_use_dynamodb_or_bigtable",
    question: "¿Cuándo recomendarías adoptar motores clave-valor de latencia ultrabaja como DynamoDB o Cloud Bigtable frente a bases documentales?",
    enText: "I recommend key-value engines like DynamoDB or Bigtable when access patterns are strictly keyed by primary partitions and require single-digit millisecond write throughput at petabyte scale. For flexible query filters, complex nested payloads, and evolving schemas, document databases like DocumentDB or Firestore remain far more productive.",
    esText: "Recomiendo motores clave-valor como DynamoDB o Bigtable cuando los patrones de acceso son estrictamente por clave primaria y exigen latencias de escritura de un solo dígito de milisegundo a escala de petabytes. Para filtros flexibles, estructuras anidadas y esquemas en evolución, las bases documentales como DocumentDB o Firestore resultan mucho más productivas.",
    category: "Technical",
    tags: ["dynamodb", "bigtable", "nosql", "key-value", "document-store", "trade-offs"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_data_modeling_embed_vs_reference",
    question: "¿Cómo decides cuándo embeber subdocumentos frente a normalizar mediante referencias en bases NoSQL?",
    enText: "I embed subdocuments when data is queried together atomically and stays well below document size boundaries like sixteen megabytes. When child entities grow unboundedly or require independent concurrent updates, referencing keys alongside application-level joining prevents write contention.",
    esText: "Embebo subdocumentos cuando los datos se consultan juntos de forma atómica y se mantienen holgadamente bajo el límite de tamaño de documento de dieciséis megabytes. Cuando las entidades crecen de forma ilimitada o requieren actualizaciones concurrentes independientes, referenciar claves evita cuellos de botella por contención.",
    category: "Technical",
    tags: ["data-modeling", "embedding", "referencing", "nosql", "documents", "contention"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_indexing_strategies_nosql",
    question: "¿Qué principios aplicas para diseñar índices eficientes y prevenir sobrecostos de escritura en colecciones NoSQL masivas?",
    enText: "I design compound indexes adhering strictly to the Equality, Sort, Range rule and leverage partial or sparse indexing to exclude null records. Limiting the total index count per collection prevents write amplification and conserves RAM for working set caching.",
    esText: "Diseño índices compuestos siguiendo estrictamente la regla de Igualdad, Ordenamiento y Rango, aplicando indexación parcial o dispersa para excluir registros nulos. Limitar la cantidad total de índices por colección previene la amplificación de escrituras y preserva la memoria RAM para el working set.",
    category: "Technical",
    tags: ["indexing", "compound index", "write amplification", "esr rule", "performance"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_ttl_indexes_archiving",
    question: "¿Cómo gestionas el ciclo de vida de datos y la purga automática en colecciones NoSQL de alto volumen?",
    enText: "I configure native TTL indexes on timestamp fields for ephemeral sessions and stream aged audit records to cold object storage using Kafka CDC pipelines. This automated retention strategy keeps active indexes lean and eliminates expensive periodic manual batch deletion queries.",
    esText: "Configuro índices TTL nativos sobre marcas de tiempo para sesiones efímeras y exporto auditorías históricas hacia almacenamiento en frío usando pipelines de CDC con Kafka. Esta retención automatizada mantiene livianos los índices y elimina costosas consultas periódicas de borrado masivo.",
    category: "Technical",
    tags: ["ttl", "retention", "purging", "lifecycle", "cdc", "kafka"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 4: SHARDING, SEGMENTACIÓN & PARTICIONAMIENTO
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_database_sharding_segmentation",
    question: "¿Qué estrategias utilizas para la segmentación de bases de datos y sharding en sistemas de alto tráfico?",
    enText: "I design horizontal sharding using high-cardinality partition keys paired with consistent hashing to prevent cluster hot spots. Isolating large enterprise tenants onto dedicated physical shards while packing smaller workloads maintains predictable P99 latency during traffic spikes.",
    esText: "Diseño sharding horizontal combinando claves de partición de alta cardinalidad con hashing consistente para prevenir puntos calientes en el cluster. Aislar grandes tenants en shards físicos dedicados mientras se agrupan cargas menores mantiene predecible la latencia P99 durante picos de tráfico.",
    category: "Technical",
    tags: ["sharding", "segmentación", "partitioning", "hotspots", "scaling", "latency"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_shard_key_selection",
    question: "¿Cuáles son los criterios clave para elegir una Shard Key adecuada en sistemas de alto rendimiento?",
    enText: "An effective shard key requires high cardinality, uniform write distribution, and alignment with the most frequent query filters. Choosing monotonically increasing timestamps causes severe write hotspots on the newest partition, making salted or hashed composite keys far superior.",
    esText: "Una shard key efectiva requiere alta cardinalidad, distribución uniforme de escrituras y alineación con los filtros de consulta más frecuentes. Elegir marcas de tiempo secuenciales genera puntos calientes en la partición más reciente, por lo que utilizar claves compuestas con salting o hashing es indispensable.",
    category: "Technical",
    tags: ["shard key", "cardinality", "monotony", "hotspots", "partitioning"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_scatter_gather_queries",
    question: "¿Por qué las consultas dispersas (scatter-gather) degradan el rendimiento y cómo las evitas?",
    enText: "Scatter-gather queries broadcast requests to all cluster partitions simultaneously, making overall latency bound to the slowest responding node. Enforcing query routing by partition key at the API gateway layer ensures queries target exactly one shard directly.",
    esText: "Las consultas scatter-gather transmiten peticiones a todas las particiones simultáneamente, atando la latencia global al nodo de respuesta más lento. Exigir la clave de partición en la capa de gateway asegura que cada consulta apunte directamente a un único shard.",
    category: "Technical",
    tags: ["scatter-gather", "sharding", "latency", "routing", "gateway"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_consistent_hashing_virtual_nodes",
    question: "¿Cómo funciona el hashing consistente con nodos virtuales y qué problema resuelve al escalar clusters NoSQL?",
    enText: "Consistent hashing maps partition keys and cluster nodes onto a circular ring, minimizing data rebalancing when adding or removing storage instances. Introducing virtual nodes distributes multiple ring points per physical server, ensuring balanced CPU and disk utilization across heterogenous machines.",
    esText: "El hashing consistente distribuye claves y nodos sobre un anillo circular, minimizando la migración de datos al agregar o quitar instancias de almacenamiento. Incorporar nodos virtuales asigna múltiples puntos del anillo por servidor físico, garantizando un reparto equitativo de carga entre máquinas heterogéneas.",
    category: "Technical",
    tags: ["consistent hashing", "virtual nodes", "rebalancing", "scaling", "ring"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_resharding_without_downtime",
    question: "¿Cómo ejecutarías un re-sharding de base de datos en producción sin interrumpir el tráfico en vivo?",
    enText: "I execute live re-sharding by orchestrating dual-write replication to the new topology alongside an asynchronous background backfill worker. A lightweight routing proxy validates checksum parity on shadow traffic before flipping the active routing table over transparently.",
    esText: "Ejecuto re-sharding en vivo orquestando doble escritura sobre la nueva topología combinada con sincronización histórica en segundo plano. Un proxy de ruteo valida paridad de checksums mediante tráfico sombra antes de conmutar la tabla de ruteo activa de forma transparente.",
    category: "Technical",
    tags: ["resharding", "zero downtime", "dual-write", "backfill", "proxy"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 5: PROXIES DE BASE DE DATOS & QUERY GATEWAYS
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_centralized_query_gateway",
    question: "¿Cómo diseñarías un mecanismo de gestión centralizada de consultas y proxy para bases de datos NoSQL?",
    enText: "A centralized query gateway manages connection multiplexing, dynamic query routing by partition key, and circuit breaking before hitting storage nodes. This architecture shields database clusters from connection exhaustion while enabling transparent live cluster migrations with zero application downtime.",
    esText: "Un gateway centralizado de consultas gestiona multiplexación de conexiones, ruteo dinámico por clave de partición y circuit breaking antes de tocar los nodos de almacenamiento. Esta arquitectura protege los clusters contra saturación de conexiones y permite migraciones en caliente sin downtime.",
    category: "Technical",
    tags: ["proxy", "query gateway", "connection pooling", "routing", "throttling", "downtime"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_connection_pooling_multiplexing",
    question: "¿Cómo previene un proxy de bases de datos el agotamiento de sockets (socket exhaustion) en microservicios masivos?",
    enText: "The proxy maintains persistent, warmed connection pools toward storage instances and multiplexes hundreds of ephemeral microservice client requests across those pooled sockets. This decouples application client concurrency from backend process limits, suppressing CPU context switching on storage engines.",
    esText: "El proxy mantiene pools persistentes y precalentados hacia el almacenamiento, multiplexando cientos de conexiones efímeras de microservicios sobre dichos sockets compartidos. Esto desacopla la concurrencia de clientes de los límites del motor, eliminando sobrecarga por context switching en los nodos de datos.",
    category: "Technical",
    tags: ["connection pooling", "multiplexing", "socket exhaustion", "proxy", "concurrency"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_read_write_splitting",
    question: "¿Cómo manejas la segregación de lecturas y escrituras (read/write splitting) a nivel de proxy de base de datos?",
    enText: "The gateway inspects wire protocol opcodes, routing writes to the primary node while distributing read queries across read replicas using weighted round-robin. For post-write workflows, tracking transaction replication watermarks ensures clients immediately read their own writes without stale read anomalies.",
    esText: "El gateway inspecciona los opcodes del protocolo, enviando escrituras al nodo primario y distribuyendo lecturas entre réplicas mediante round-robin ponderado. Para flujos posteriores a una escritura, registrar la marca de replicación asegura que el cliente lea sus propios cambios sin inconsistencias.",
    category: "Technical",
    tags: ["read-write splitting", "replicas", "routing", "primary", "watermark"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_rate_limiting_token_bucket",
    question: "¿Cómo implementarías rate limiting en un proxy de bases de datos para proteger clusters contra consultas abusivas?",
    enText: "I implement token bucket rate limiting in the database gateway keyed by client service identity and query complexity weight. Queries exceeding dynamic concurrency thresholds are gracefully queued or rejected with specific backoff codes before saturating backend storage engines.",
    esText: "Implemento rate limiting por token bucket en el gateway de base de datos categorizado por identidad del microservicio y costo estimado de la consulta. Las peticiones que superan los umbrales de concurrencia se encolan o rechazan con códigos de backoff antes de saturar los motores de almacenamiento.",
    category: "Technical",
    tags: ["rate limiting", "token bucket", "throttling", "proxy", "dos prevention"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_transparent_failover_proxy",
    question: "¿Cómo gestiona el proxy de base de datos un failover del nodo primario sin desconectar a las aplicaciones?",
    enText: "When the primary storage node fails health checks, the proxy buffers incoming writes in memory for a few seconds while promoting an in-sync replica. Once the new primary registers, buffered operations replay seamlessly without throwing connection resets to caller services.",
    esText: "Cuando el nodo primario falla los health checks, el proxy retiene en memoria las escrituras entrantes durante breves segundos mientras se promueve una réplica sincronizada. Una vez activo el nuevo primario, las operaciones encoladas se ejecutan sin arrojar errores de desconexión a las aplicaciones.",
    category: "Technical",
    tags: ["failover", "high availability", "proxy", "buffering", "zero downtime"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 6: ISTIO, SERVICE MESH & KUBERNETES
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_istio_modernization",
    question: "¿Cómo abordarías la migración de arquitecturas heredadas hacia Istio o arquitecturas de despliegue modernas en Kubernetes?",
    enText: "I migrate services incrementally to Istio by deploying Envoy sidecars per namespace and validating service latencies before enforcing strict mTLS. Offloading mutual TLS encryption and canary traffic routing directly to the service mesh minimizes application code modifications.",
    esText: "Migro servicios de forma incremental hacia Istio inyectando sidecars de Envoy por namespace y validando latencias antes de exigir mTLS estricto. Delegar el cifrado mutuo y el ruteo canary directamente al service mesh minimiza cualquier modificación en el código de aplicación.",
    category: "Technical",
    tags: ["istio", "kubernetes", "service mesh", "envoy", "mtls", "canary", "serverless"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_envoy_sidecar_latency_overhead",
    question: "¿Cómo monitoreas y minimizas el impacto de latencia que agregan los sidecars de Envoy en consultas de bases de datos?",
    enText: "I optimize Envoy by tuning thread concurrency, sizing memory buffers, and leveraging shared memory domain sockets between the application container and sidecar. Continuous benchmark tracking ensures the proxy hop contributes less than zero point five milliseconds of overhead to overall latency.",
    esText: "Optimizo Envoy ajustando la concurrencia de hilos, dimensionando buffers de memoria y utilizando sockets de dominio UNIX compartidos entre el contenedor y el sidecar. Monitorear benchmarks continuos garantiza que el salto del proxy agregue menos de medio milisegundo a la latencia total.",
    category: "Technical",
    tags: ["envoy", "sidecar", "latency", "tuning", "domain sockets"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_istio_mtls_permissive_to_strict",
    question: "¿Cuál es la estrategia para pasar de modo permisivo a estricto en mTLS sin romper microservicios productivos?",
    enText: "I enforce permissive mode initially to allow both plaintext and encrypted traffic while auditing Envoy telemetry for unauthenticated service connections. Once metrics confirm all communicating workloads present valid SPIFFE certificates, enforcing strict PeerAuthentication guarantees complete transport security without incidents.",
    esText: "Inicio en modo permisivo para habilitar tráfico cifrado y en texto plano en paralelo mientras audito la telemetría de Envoy en busca de conexiones sin certificado. Cuando las métricas confirman que todos los workloads presentan certificados SPIFFE válidos, activar modo estricto garantiza seguridad total sin incidentes.",
    category: "Technical",
    tags: ["mtls", "spiffe", "peerauthentication", "istio", "security", "rollout"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_workload_identity_kubernetes",
    question: "¿Cómo reemplazas credenciales estáticas de bases de datos utilizando Kubernetes Workload Identity?",
    enText: "I map Kubernetes Service Accounts directly to cloud IAM roles through Workload Identity, issuing short-lived cryptographic tokens automatically to running pods. This architecture completely eliminates static database passwords from git repositories, container images, and runtime configuration maps.",
    esText: "Asocio Service Accounts de Kubernetes directamente a roles IAM mediante Workload Identity, entregando tokens criptográficos efímeros a los pods en ejecución. Esta arquitectura elimina contraseñas estáticas de bases de datos en repositorios, imágenes y archivos de configuración.",
    category: "Technical",
    tags: ["workload identity", "iam", "kubernetes", "secrets", "security", "credentials"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 7: LATENCIA P99, RENDIMIENTO & CACHE DISTRIBUIDO
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_p99_latency_caching",
    question: "¿Cómo optimizas la latencia P99 y previenes el efecto estampida (thundering herd) en bases de datos NoSQL?",
    enText: "I place a distributed Redis caching layer in front of the database using cache-aside and singleflight mutexes. This guarantees that only one worker queries the storage engine during cache misses, suppressing the thundering herd and stabilizing tail latencies.",
    esText: "Coloco una capa de cache distribuido en Redis frente a la base de datos aplicando cache-aside y mutexes singleflight. Esto garantiza que un único worker consulte el motor de almacenamiento ante misses de cache, eliminando estampidas y estabilizando la latencia de cola.",
    category: "Technical",
    tags: ["latency", "p99", "redis", "caching", "thundering herd", "performance"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_hot_keys_redis_black_friday",
    question: "¿Cómo gestionas claves hiperactivas (hot keys) en Redis durante eventos pico como Hot Sale o Black Friday?",
    enText: "I mitigate hot keys by appending random salt suffixes to distribute key reads across multiple Redis nodes and implementing local in-process LRU caching for ultra-hot items. Replicating hot records locally cuts network round trips and keeps Redis cluster memory bandwidth within safe margins.",
    esText: "Mitigo claves calientes agregando sufijos aleatorios para distribuir las lecturas entre múltiples nodos de Redis e implementando caching local LRU en memoria de proceso para ítems virales. Replicar localmente evita saltos de red y mantiene el ancho de banda del cluster en márgenes seguros.",
    category: "Technical",
    tags: ["redis", "hot keys", "black friday", "lru", "salting", "caching"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_cache_invalidation_event_driven",
    question: "¿Cuál es tu estrategia para la invalidación de cache y el mantenimiento de consistencia con la base de datos?",
    enText: "I rely on asynchronous cache invalidation driven by Change Data Capture events from Kafka rather than error-prone application write-path purges. Setting defensive TTLs alongside event-driven eviction ensures eventual consistency even if network partitions delay event consumer processing.",
    esText: "Implemento invalidación asíncrona guiada por eventos de Change Data Capture desde Kafka en lugar de purgas manuales en el flujo de escritura de la aplicación. Configurar TTLs defensivos junto con desalojo por eventos garantiza consistencia eventual ante demoras de red en los consumidores.",
    category: "Technical",
    tags: ["cache invalidation", "cdc", "kafka", "ttl", "consistency"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_tail_latency_causes",
    question: "¿Cuáles son las causas más comunes de picos en la latencia de cola (P99) y cómo las investigas?",
    enText: "Tail latency spikes typically stem from garbage collection pauses, unindexed queries performing table scans, or TCP connection retransmissions under network saturation. I correlate distributed traces in Jaeger with host kernel metrics like disk IOPS and run queue depth to pinpoint the exact bottleneck.",
    esText: "Los picos de latencia de cola suelen originarse por pausas de garbage collection, consultas sin índice realizando scans completos o retransmisiones TCP por saturación de red. Correlaciono trazas distribuidas en Jaeger con métricas de kernel como IOPS y profundidad de runqueue para aislar el cuello de botella.",
    category: "Technical",
    tags: ["tail latency", "p99", "jaeger", "gc", "table scan", "diagnostics"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 8: CONSISTENCIA, PACELC & EVENT-DRIVEN
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_consistency_cap_pacelc",
    question: "¿Cómo balanceas consistencia vs disponibilidad en sistemas NoSQL distribuidos bajo el teorema PACELC?",
    enText: "I tune read and write concerns according to business criticality, using strong quorum consistency for financial transactions and eventual consistency for high-volume telemetry. Pairing idempotent writes with asynchronous read repair maintains ninety-nine point nine percent availability without sacrificing critical data integrity.",
    esText: "Ajusto las garantías de lectura y escritura según la criticidad del negocio, usando consistencia estricta por quórum en transacciones y consistencia eventual en telemetría masiva. Combinar escrituras idempotentes con read repair asíncrono sostiene alta disponibilidad sin comprometer la integridad de datos críticos.",
    category: "Technical",
    tags: ["cap", "pacelc", "consistency", "eventual consistency", "quorum", "distributed"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_idempotency_patterns",
    question: "¿Cómo aseguras idempotencia en operaciones de escritura concurrentes en bases de datos NoSQL?",
    enText: "I enforce idempotency by extracting unique client request tokens and persisting them in a dedicated unique index collection before executing mutations. Replayed or duplicated network requests retrieve the cached outcome immediately without executing duplicate state changes.",
    esText: "Aseguro idempotencia extrayendo tokens únicos de petición y registrándolos con un índice único antes de aplicar mutaciones en los datos. Peticiones duplicadas o reintentos de red recuperan el resultado previo de inmediato sin volver a ejecutar modificaciones de estado.",
    category: "Technical",
    tags: ["idempotency", "unique index", "tokens", "mutations", "reliability"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_transactional_outbox_pattern",
    question: "¿Qué es el patrón Transactional Outbox y cómo resuelve la consistencia dual entre base de datos y Kafka?",
    enText: "The transactional outbox pattern writes business entities and event records into the same database atomically within a single local transaction. A dedicated background change data capture process streams outbox records to Kafka, guaranteeing reliable at-least-once message publication without distributed two-phase commits.",
    esText: "El patrón transactional outbox registra la entidad de negocio y el evento en la misma base de datos de forma atómica dentro de una única transacción local. Un proceso de Change Data Capture transmite los registros hacia Kafka, garantizando publicación confiable sin requerir costosos commits en dos fases.",
    category: "Technical",
    tags: ["outbox pattern", "kafka", "cdc", "consistency", "events"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_zero_downtime_migration",
    question: "¿Cuál es tu metodología para migrar datos entre motores NoSQL diferentes sin interrumpir el servicio?",
    enText: "I implement dual-writing through feature flags followed by Change Data Capture backfilling with Kafka to sync historical state. Once asynchronous validation confirms zero checksum discrepancies between engines, we switch read traffic over transparently.",
    esText: "Implemento doble escritura mediante feature flags seguida de sincronización histórica con Change Data Capture y Kafka. Una vez que la validación asíncrona confirma cero discrepancias de checksum entre ambos motores, conmutamos las lecturas de forma transparente.",
    category: "Technical",
    tags: ["migration", "zero downtime", "dual-write", "cdc", "kafka", "feature flags"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 9: PYTHON ASÍNCRONO & BACKEND DE ALTO RENDIMIENTO
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_python_async_perf",
    question: "¿Cómo aseguras alto rendimiento y no bloqueas el event loop al construir servicios con Python y FastAPI?",
    enText: "I ensure non-blocking I/O by utilizing async native database drivers and delegating CPU-heavy tasks to worker pools or Celery queues. Combining connection reuse with uvloop keeps API response times predictable under thousands of concurrent requests.",
    esText: "Garantizo I/O no bloqueante utilizando drivers nativos asíncronos y delegando tareas pesadas de CPU a pools de procesos o workers en Celery. Combinar reutilización de conexiones con uvloop mantiene los tiempos de respuesta estables bajo miles de peticiones concurrentes.",
    category: "Technical",
    tags: ["python", "asyncio", "fastapi", "performance", "uvloop", "concurrency"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_python_memory_leaks_profiling",
    question: "¿Cómo diagnosticas fugas de memoria o cuellos de botella de CPU en microservicios Python en producción?",
    enText: "I profile running services using py-spy and tracemalloc to capture call stacks and memory allocation deltas without stopping production workers. Eliminating unclosed database client sessions and cyclic references typically stabilizes memory consumption under heavy request loads.",
    esText: "Perfilo servicios en producción utilizando py-spy y tracemalloc para inspeccionar llamadas y deltas de memoria sin interrumpir los procesos productivos. Cerrar sesiones de base de datos no liberadas y romper referencias circulares estabiliza de inmediato el consumo de memoria.",
    category: "Technical",
    tags: ["python", "memory leaks", "py-spy", "profiling", "tracemalloc"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_serialization_speed_python",
    question: "¿Cómo optimizas la serialización de documentos JSON masivos entre Python y la base de datos?",
    enText: "I replace standard library JSON parsers with native Rust-backed libraries like orjson and leverage Pydantic version two for schema validation. This accelerates document serialization throughput by over five times while reducing CPU overhead on high-throughput microservices.",
    esText: "Reemplazo el serializador JSON estándar por bibliotecas de alto rendimiento en Rust como orjson y aplico Pydantic versión dos para validación de esquemas. Esto quintuplica la velocidad de serialización de documentos reduciendo drásticamente el consumo de CPU en servicios masivos.",
    category: "Technical",
    tags: ["serialization", "orjson", "pydantic", "json", "python", "performance"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 10: HISTORIAS STAR & CASOS REALES DE LOS CVS
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_troubleshooting_incident_star",
    question: "Cuéntame sobre una situación crítica de degradación de rendimiento o saturación de base de datos que hayas resuelto.",
    enText: "During an enrollment traffic spike, database connection exhaustion caused severe latency spikes across our core services. I deployed connection pooling in transaction mode alongside Redis caching, reducing active database connections by eighty percent and restoring sub-twenty millisecond P95 latencies.",
    esText: "Durante un pico de inscripciones, el agotamiento de conexiones de base de datos disparó la latencia en nuestros servicios críticos. Desplegué pooling de conexiones en modo transacción junto con cache en Redis, reduciendo las conexiones activas en un 80% y normalizando la latencia P95 bajo 20 milisegundos.",
    category: "Behavioral",
    tags: ["star", "incident", "troubleshooting", "latency", "pooling", "redis", "resilience"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_hot_shard_incident_star",
    question: "¿Cómo diagnosticaste y mitigaste un problema de partición caliente (hot shard) en un cluster NoSQL?",
    enText: "Prometheus alerts flagged a single storage node operating at ninety percent CPU due to unpartitioned viral entity queries. I applied salt hashing to the partition key and introduced short-lived edge caching, evenly redistributing IOPS across nodes without data loss.",
    esText: "Alertas de Prometheus detectaron un nodo de almacenamiento al 90% de CPU por consultas concentradas sobre una misma entidad viral. Apliqué salting en la clave de partición e introduje caching efímero en el borde, redistribuyendo los IOPS equitativamente entre los nodos sin pérdida de datos.",
    category: "Behavioral",
    tags: ["star", "hot shard", "partitioning", "prometheus", "salting", "troubleshooting"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_technical_disagreement_star",
    question: "Cuéntame sobre un desacuerdo técnico en tu equipo sobre arquitectura y cómo lo resolviste.",
    enText: "My team disagreed on whether to migrate our storage cluster to a new managed engine or optimize existing sharding. I led a timeboxed benchmarking spike comparing read and write latencies under peak traffic loads, aligning the team around data-driven results documented in an ADR.",
    esText: "En mi equipo discrepábamos entre migrar nuestro cluster de datos hacia un nuevo motor administrado u optimizar el sharding actual. Lideré un spike comparativo evaluando latencias bajo carga de pico real, logrando consenso técnico basado en datos que documentamos en un ADR.",
    category: "Behavioral",
    tags: ["star", "disagreement", "teamwork", "benchmarking", "adr", "consensus"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_failed_deployment_star",
    question: "Cuéntame sobre una falla en producción después de un despliegue y cómo la manejaste.",
    enText: "A configuration rollout introduced unexpected query timeouts on a subset of database replica nodes during afternoon traffic. I immediately executed an automated canary rollback and identified an oversized connection timeout parameter, restoring normal platform operations within four minutes.",
    esText: "Un despliegue de configuración introdujo timeouts inesperados en réplicas de lectura durante el tráfico de la tarde. Ejecuté de inmediato un rollback automatizado del canary e identifiqué un valor excesivo de timeout en los clientes, restableciendo el servicio en cuatro minutos.",
    category: "Behavioral",
    tags: ["star", "postmortem", "rollback", "canary", "resilience", "production"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 11: USO DE INTELIGENCIA ARTIFICIAL EN INGENIERÍA
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_ai_daily_workflow",
    question: "¿Cómo incorporas herramientas de inteligencia artificial en tu flujo de trabajo diario de ingeniería de software?",
    enText: "I use AI daily to synthesize edge-case unit test suites, benchmark complex queries, and validate Kubernetes security policies before code reviews. This automation eliminates repetitive setup work so I can dedicate focus to distributed systems reliability and low-latency proxy architectures.",
    esText: "Utilizo IA a diario para sintetizar suites de tests con casos de borde, benchmarkear consultas complejas y auditar políticas de seguridad en Kubernetes antes del code review. Esta automatización elimina tareas repetitivas para enfocarme en confiabilidad de sistemas distribuidos y proxies de baja latencia.",
    category: "Technical",
    tags: ["ai", "inteligencia artificial", "copilot", "workflow", "productivity", "testing"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_ai_test_generation",
    question: "¿De qué manera utilizas LLMs para mejorar la cobertura de pruebas y calidad de código?",
    enText: "I prompt LLMs with database boundary conditions to generate property-based tests and mock out complex network failure scenarios. Verifying generated test suites against strict mutation testing ensures we catch subtle distributed edge cases without relying on blind code generation.",
    esText: "Utilizo LLMs definiendo condiciones de borde de base de datos para generar pruebas de propiedades y simular escenarios complejos de desconexión de red. Validar los tests generados mediante mutation testing asegura detectar casos de borde distribuidos sin depender de código a ciegas.",
    category: "Technical",
    tags: ["ai", "testing", "mutation testing", "edge cases", "quality"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_ai_code_review_security",
    question: "¿Cómo empleas herramientas de IA para auditar seguridad en infraestructura como código y políticas cloud?",
    enText: "I integrate LLMs into pre-commit workflows to audit Terraform configurations and Kubernetes manifests against CIS benchmarks and least-privilege standards. Catching over-permissive IAM bindings and unencrypted storage volumes before deployment drastically strengthens platform security posture.",
    esText: "Integro LLMs en workflows de pre-commit para auditar manifiestos de Terraform y Kubernetes contra estándares CIS y políticas de menor privilegio. Detectar permisos IAM excesivos y volúmenes sin cifrado antes del despliegue fortalece notablemente la seguridad de la plataforma.",
    category: "Technical",
    tags: ["ai", "security", "terraform", "kubernetes", "cis benchmarks", "audit"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 12: SEGURIDAD, CIFRADO & GOBERNANZA DE DATOS
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_security_encryption_rbac",
    question: "¿Cómo implementas seguridad, cifrado y controles de acceso en plataformas de bases de datos críticas?",
    enText: "I implement envelope encryption at rest using KMS managed keys and enforce TLS one point three in transit via Istio. Access is governed through Kubernetes Workload Identity and strict least-privilege IAM policies, eliminating hardcoded service credentials completely.",
    esText: "Implemento envelope encryption en reposo con claves gestionadas en KMS y exijo TLS 1.3 en tránsito mediante Istio. El acceso se controla con Kubernetes Workload Identity y políticas IAM de menor privilegio, eliminando credenciales estáticas en los servicios.",
    category: "Technical",
    tags: ["security", "encryption", "rbac", "iam", "kms", "compliance", "seguridad"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_data_masking_pii",
    question: "¿Cómo proteges datos sensibles (PII / PCI) en capas de bases de datos y registros de telemetría?",
    enText: "I enforce automated field-level encryption for sensitive attributes before persisting documents and strip confidential data at proxy egress layers. Exported application logs and distributed traces automatically sanitize customer identifiers to maintain strict financial regulatory compliance.",
    esText: "Aplico cifrado a nivel de campo para atributos confidenciales antes de persistir documentos y filtro datos sensibles en la salida del proxy. Los logs y trazas distribuidas sanitizan automáticamente identificadores de clientes para garantizar cumplimiento regulatorio financiero.",
    category: "Technical",
    tags: ["security", "pii", "pci", "masking", "encryption", "compliance"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 13: OBSERVABILIDAD, MONITORING & SRE
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_observability_golden_signals",
    question: "¿Qué métricas y herramientas de observabilidad priorizas para monitorear plataformas NoSQL a gran escala?",
    enText: "I track the four golden signals with emphasis on P99 latency percentiles, storage node saturation, and query connection pool utilization. Exporting OpenTelemetry traces to Jaeger allows us to pinpoint slow database queries across distributed microservices immediately.",
    esText: "Monitoreo las cuatro señales doradas priorizando percentiles P99 de latencia, saturación de nodos de almacenamiento y utilización del pool de conexiones. Exportar trazas OpenTelemetry hacia Jaeger permite identificar al instante consultas lentas a través de los microservicios distribuidos.",
    category: "Technical",
    tags: ["observability", "metrics", "golden signals", "opentelemetry", "jaeger", "prometheus"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_slo_sli_error_budget",
    question: "¿Cómo defines SLIs, SLOs y presupuestos de error (Error Budgets) para un servicio central de bases de datos?",
    enText: "I define availability SLIs based on the ratio of non-five-hundred responses and latency SLIs targeting ninety-nine percent of queries completing under twenty milliseconds. When error budgets deplete, automated alerts throttle non-critical background jobs to protect critical transaction capacity.",
    esText: "Defino el SLI de disponibilidad midiendo la proporción de respuestas exitosas y el SLI de latencia exigiendo que el 99% de las consultas finalicen bajo 20 milisegundos. Al agotarse el error budget, se postergan tareas de fondo no críticas para preservar capacidad operativa transaccional.",
    category: "Technical",
    tags: ["slo", "sli", "error budget", "sre", "metrics", "availability"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_distributed_tracing_opentelemetry",
    question: "¿Cómo propagas contexto de trazabilidad distribuida a través de proxies y clientes de base de datos?",
    enText: "I inject standard W3C tracecontext headers into outgoing requests and propagate trace spans through proxy middleware down into database query comments. This end-to-end correlation connects upstream user frontend requests directly to specific storage engine executions in Jaeger.",
    esText: "Inyecto encabezados estándares W3C tracecontext en las peticiones y propago los spans a través del proxy agregando identificadores en comentarios de las consultas. Esta correlación punta a punta vincula directamente acciones de usuarios en el frontend con ejecuciones específicas de almacenamiento en Jaeger.",
    category: "Technical",
    tags: ["opentelemetry", "tracing", "w3c", "jaeger", "sql comments", "correlation"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 14: RESILIENCIA & MANEJO DE FALLAS
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_resilience_circuit_breaker",
    question: "¿Cómo previenes fallas en cascada cuando una base de datos o servicio downstream experimenta degradación?",
    enText: "I configure circuit breakers and exponential backoff with jitter on outgoing database queries to shed downstream load fast. Enforcing bulkhead thread pool isolation prevents a degraded storage partition from exhausting system memory across healthy workloads.",
    esText: "Configuro circuit breakers y backoff exponencial con jitter en las consultas salientes para aliviar la carga downstream rápidamente. Aplicar aislamiento por bulkheads evita que una partición degradada agote la memoria y recursos del resto de los servicios saludables.",
    category: "Technical",
    tags: ["resilience", "circuit breaker", "bulkhead", "backoff", "cascading failure"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_split_brain_prevention",
    question: "¿Cómo previene un cluster NoSQL distribuido el problema de cerebro dividido (split-brain) durante cortes de red?",
    enText: "Distributed storage engines prevent split-brain by requiring strict odd-numbered majority quorums for electing primary nodes and accepting write operations. If a network partition isolates a minority node group, those instances automatically reject writes and transition to read-only replica status.",
    esText: "Los motores de almacenamiento previenen el cerebro dividido exigiendo quórum por mayoría impar para elegir nodos primarios y aceptar escrituras. Si una partición de red aísla a una minoría, esas instancias rechazan escrituras automáticamente y operan como réplicas de solo lectura.",
    category: "Technical",
    tags: ["split-brain", "quorum", "consensus", "high availability", "network partition"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 15: PREGUNTAS DE ORO PARA EL ENTREVISTADOR
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_reverse_questions_scaling",
    question: "¿Tienes alguna pregunta para nosotros sobre los desafíos técnicos del equipo?",
    enText: "I'd love to know what the biggest operational bottleneck is today when scaling DocumentDB clusters across regions, and how you see the balance between building in-house database proxies versus adopting open-source solutions evolving over the next year.",
    esText: "Me gustaría conocer cuál es el mayor cuello de botella operativo actual al escalar clusters de DocumentDB entre regiones, y cómo proyectan en el equipo el balance entre desarrollar proxies propietarios versus adoptar herramientas open-source durante el próximo año.",
    category: "Screening",
    tags: ["reverse questions", "preguntas", "cierre", "interviewer"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_reverse_questions_team_metrics",
    question: "¿Qué métricas o logros definirían que la persona en este rol tuvo un impacto exitoso durante sus primeros seis meses?",
    enText: "I'm curious what key technical milestones would mark success in the first six months, such as reducing P99 query latency, standardizing multi-cloud proxies, or speeding up microservice onboarding onto the NoSQL platform.",
    esText: "Tengo curiosidad por saber qué hitos técnicos marcarían el éxito en los primeros seis meses, como reducir la latencia P99, estandarizar proxies multi-nube o agilizar la adopción de la plataforma NoSQL en nuevos microservicios.",
    category: "Screening",
    tags: ["reverse questions", "success metrics", "impact", "first six months"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_reverse_questions_ai_adoption",
    question: "¿Cómo está impulsando Mercado Libre la adopción de IA generativa dentro de sus equipos centrales de plataforma?",
    enText: "How is Mercado Libre currently integrating generative AI into developer productivity workflows for core platform engineers, especially regarding automated incident triage or schema migration testing?",
    esText: "¿Cómo está impulsando Mercado Libre la adopción de IA generativa en la productividad de sus ingenieros de plataforma central, especialmente en el triage de incidentes y validación de migraciones de datos?",
    category: "Screening",
    tags: ["reverse questions", "ai", "productivity", "platform engineering"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 16: ADVANCED SYSTEMS DESIGN & SCALE LATAM
  // ══════════════════════════════════════════════════════════
  {
    id: "meli_multi_doc_acid_transactions",
    question: "¿Cuándo recurres a transacciones ACID multi-documento en NoSQL y cuáles son sus penalizaciones de rendimiento?",
    enText: "I reserve multi-document ACID transactions strictly for critical financial balances where compensating sagas are unviable, keeping operations bounded to very few documents. In distributed document stores, multi-shard transactions lock resources and escalate latency P99 significantly under write contention.",
    esText: "Reservo transacciones ACID multi-documento estrictamente para balances financieros críticos donde las sagas compensatorias no son viables, limitando la operación a muy pocos documentos. En bases distribuidas, las transacciones multi-shard retienen locks y disparan la latencia P99 ante contención de escrituras.",
    category: "Technical",
    tags: ["acid", "transactions", "nosql", "locking", "latency", "finance"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_proxy_backpressure_memory_safety",
    question: "¿Cómo implementas contrapresión (backpressure) en un proxy de bases de datos para evitar que se quede sin memoria RAM?",
    enText: "I enforce bounded ring buffers on incoming client request queues and pause socket reads when database execution latency begins degrading. If upstream microservices exceed memory saturation thresholds, the proxy immediately emits HTTP four-twenty-nine or connection reject signals to shed load safely.",
    esText: "Implemento buffers circulares acotados en las colas de peticiones y pauso la lectura de sockets cuando la latencia del motor comienza a degradarse. Si los microservicios aguas arriba superan los umbrales de saturación, el proxy emite señales de rechazo inmediato para aliviar la carga de forma segura.",
    category: "Technical",
    tags: ["backpressure", "proxy", "memory safety", "ring buffer", "load shedding"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_hot_sale_prewarming_capacity",
    question: "¿Cómo planificas la capacidad y precalentamiento (pre-warming) de bases NoSQL antes de Hot Sale o Black Friday?",
    enText: "I analyze historical traffic peaks to provision storage compute instances and pre-warm connection pools and caches forty-eight hours before the event starts. Running automated synthetic load tests through shadow proxies validates that auto-scaling thresholds trigger well before organic user traffic hits peak volume.",
    esText: "Analizo picos históricos de tráfico para aprovisionar instancias de cómputo y precalentar pools de conexiones y caches 48 horas antes del evento. Ejecutar pruebas de carga sintética mediante proxies de shadow traffic confirma que el autoescalado responda antes de la llegada del tráfico masivo orgánico.",
    category: "Technical",
    tags: ["capacity planning", "pre-warming", "hot sale", "black friday", "autoscaling"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: true,
    createdAt: 1789572000000,
  },
  {
    id: "meli_cdc_debezium_search_indexing",
    question: "¿Cómo sincronizas colecciones NoSQL con motores de búsqueda como Elasticsearch u OpenSearch mediante CDC?",
    enText: "I capture document mutation streams via Debezium or native change streams, routing filtered events into partitioned Kafka topics with entity keys. Downstream indexing microservices consume batches asynchronously to update Elasticsearch inverted indexes without inducing read overhead on the primary transactional database.",
    esText: "Capturo flujos de mutación de documentos mediante Debezium o change streams nativos, enrutando eventos filtrados hacia tópicos de Kafka particionados por entidad. Microservicios indexadores consumen lotes de forma asíncrona para actualizar índices en Elasticsearch sin generar sobrecarga sobre la base transaccional.",
    category: "Technical",
    tags: ["cdc", "debezium", "kafka", "elasticsearch", "opensearch", "indexing"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_raft_vs_paxos_consensus",
    question: "¿Qué rol juegan algoritmos de consenso como Raft o Paxos en la tolerancia a fallos de bases de datos distribuidas?",
    enText: "Consensus algorithms ensure that a distributed cluster reaches unanimous agreement on transaction log ordering despite arbitrary machine failures or network latency. Paxos excels in multi-region active-active topologies like Spanner and Firestore, while Raft offers simplified leader election in systems like etcd and MongoDB.",
    esText: "Los algoritmos de consenso garantizan acuerdo unánime en el orden del log de transacciones frente a caídas de servidores o demoras de red. Paxos sobresale en topologías activo-activo multi-región como Spanner y Firestore, mientras que Raft simplifica la elección de líder en sistemas como etcd y MongoDB.",
    category: "Technical",
    tags: ["consensus", "raft", "paxos", "distributed", "replication", "fault tolerance"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_retry_storms_full_jitter",
    question: "¿Cómo previenes tormentas de reintentos (retry storms) cuando un cluster de base de datos se recupera de un incidente?",
    enText: "I enforce exponential backoff combined with full jitter on all client database drivers, randomizing retry intervals across callers. Adding circuit breakers that fail fast during outages ensures recovering storage instances are not immediately crushed by thousands of synchronized reconnects.",
    esText: "Aplico backoff exponencial combinado con full jitter en los drivers clientes de base de datos, aleatorizando los intervalos de reintento entre consumidores. Agregar circuit breakers que fallen rápido durante caídas evita que los nodos en recuperación se saturen por reconexiones sincronizadas masivas.",
    category: "Technical",
    tags: ["retry storm", "full jitter", "backoff", "circuit breaker", "resilience"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_grpc_vs_rest_database_proxies",
    question: "¿Por qué utilizar gRPC con Protocol Buffers en lugar de REST/JSON para la comunicación interna con proxies de datos?",
    enText: "gRPC multiplexes concurrent streams over a single HTTP/2 TCP connection and utilizes compact binary serialization through Protocol Buffers. This reduces network payload size by over sixty percent and eliminates CPU-intensive JSON string parsing on latency-critical proxy gateways.",
    esText: "gRPC multiplexa flujos concurrentes sobre una única conexión HTTP/2 y utiliza serialización binaria compacta mediante Protocol Buffers. Esto reduce el tamaño de las transferencias en más del 60% y elimina el costo de CPU por parseo de JSON en gateways de baja latencia.",
    category: "Technical",
    tags: ["grpc", "protobuf", "http2", "serialization", "proxy", "performance"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_zero_trust_network_policies",
    question: "¿Cómo aseguras aislamiento de red Zero-Trust alrededor de clusters NoSQL en Kubernetes?",
    enText: "I enforce strict Kubernetes NetworkPolicies that deny all ingress by default, explicitly whitelisting only designated application namespaces on database ports. Pairing this with Istio AuthorizationPolicies validates client cryptographic identity before allowing any network socket handshake.",
    esText: "Aplico NetworkPolicies estrictas en Kubernetes que deniegan todo el tráfico de entrada por defecto, habilitando únicamente los namespaces autorizados en los puertos de datos. Complementar esto con AuthorizationPolicies de Istio valida la identidad criptográfica del pod antes de abrir el socket de red.",
    category: "Technical",
    tags: ["zero trust", "networkpolicies", "kubernetes", "security", "istio"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_backup_pitr_rto_rpo",
    question: "¿Cómo diseñas estrategias de respaldo y recuperación point-in-time (PITR) con RPO y RTO mínimos?",
    enText: "I combine continuous snapshot storage volume backups with real-time transaction write-ahead log replication streaming into immutable cross-region object buckets. Automating restore drills ensures we achieve recovery point objectives under one minute and recovery time objectives under fifteen minutes.",
    esText: "Combino snapshots continuos de volúmenes de almacenamiento con replicación en tiempo real del write-ahead log hacia buckets inmutables en otra región. Automatizar simulacros periódicos de restauración asegura un RPO inferior a un minuto y un RTO menor a quince minutos.",
    category: "Technical",
    tags: ["backup", "pitr", "rpo", "rto", "disaster recovery", "storage"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_online_index_building",
    question: "¿Cómo creas índices secundarios en colecciones NoSQL de terabytes sin bloquear lecturas ni escrituras en producción?",
    enText: "I build secondary indexes strictly in background mode with throttled I/O priority, allowing the storage engine to construct B-trees incrementally across idle cycles. Once background building reaches parity with current write timestamps, the index transitions online transparently without acquiring table exclusive locks.",
    esText: "Construyo índices secundarios estrictamente en modo background con prioridad de I/O regulada, permitiendo al motor generar el árbol B de forma incremental en ciclos libres. Una vez que la indexación alcanza paridad con las escrituras actuales, el índice pasa a producción sin adquirir locks exclusivos.",
    category: "Technical",
    tags: ["indexing", "online build", "background", "nosql", "performance", "locks"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_schema_versioning_compatibility",
    question: "¿Cómo gestionas esquemas en evolución y retrocompatibilidad en bases de datos NoSQL sin downtime?",
    enText: "I apply the expand-and-contract pattern where application models treat missing fields as optional with sensible defaults before introducing new schema properties. Older microservice versions continue operating without failures while newer deployments progressively populate the updated document structure.",
    esText: "Aplico el patrón expand-and-contract donde los modelos de aplicación tratan los campos nuevos como opcionales con valores por defecto antes de migrar datos. Las versiones anteriores de los microservicios continúan operando sin fallas mientras los nuevos despliegues pueblan la estructura actualizada.",
    category: "Technical",
    tags: ["schema", "evolution", "backward compatibility", "expand contract", "migrations"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_batch_vs_online_traffic_isolation",
    question: "¿Cómo aíslas trabajos batch masivos para que no degraden las transacciones de clientes en tiempo real?",
    enText: "I route batch analytics and heavy data migration jobs strictly to dedicated read replicas configured with distinct memory limits and replica tags. Throttling batch query parallelism ensures production primary nodes maintain one hundred percent of their CPU and IOPS dedicated to customer checkout transactions.",
    esText: "Enruto procesos batch y migraciones masivas exclusivamente hacia réplicas de lectura dedicadas configuradas con límites de memoria y etiquetas aisladas. Regular el paralelismo de las consultas batch asegura que los nodos primarios dediquen el 100% de su CPU e IOPS a las compras de los usuarios.",
    category: "Technical",
    tags: ["batch", "isolation", "replicas", "throttling", "traffic management"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_blameless_postmortem_culture",
    question: "¿Cómo conduces un post-mortem sin culpas (blameless postmortem) después de una interrupción de servicio?",
    enText: "I focus post-mortems on uncovering systemic process flaws, inadequate telemetry alarms, and insufficient automated safeguards rather than attributing human error. Documenting concrete remediation items in our engineering backlog guarantees that the same failure mode cannot recur across the platform.",
    esText: "Enfoco los post-mortems en identificar fallas sistémicas, alertas de telemetría tardías y falta de defensas automatizadas en lugar de atribuir culpas individuales. Documentar planes de acción concretos en el backlog asegura que el mismo patrón de falla no vuelva a repetirse en la plataforma.",
    category: "Behavioral",
    tags: ["postmortem", "blameless", "culture", "reliability", "learning"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_mentorship_technical_leadership",
    question: "¿Cómo fomentas el crecimiento técnico y buenas prácticas en ingenieros menos experimentados del equipo?",
    enText: "I foster growth through collaborative pair programming on complex distributed bugs and structured architectural reviews where we unpack trade-offs openly. Encouraging engineers to own feature designs from concept to production telemetry builds genuine confidence and autonomous technical leadership.",
    esText: "Impulso el crecimiento técnico mediante pair programming en incidentes complejos y revisiones de arquitectura donde debatimos abiertamente los trade-offs. Incentivar a los desarrolladores a asumir el ownership de sus diseños desde el código hasta la telemetría fortalece su autonomía y liderazgo.",
    category: "Behavioral",
    tags: ["leadership", "mentorship", "team growth", "ownership", "code review"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
  {
    id: "meli_handling_ambiguity_systems",
    question: "¿Cómo abordas un problema técnico complejo cuando los requerimientos iniciales son vagos o ambiguos?",
    enText: "I break ambiguous problems down by interviewing stakeholder microservice teams to map out concrete latency targets and data volume boundaries. Formulating these requirements into clear RFCs with explicit assumptions and non-goals provides clarity and unblocks rapid iterative implementation.",
    esText: "Desgloso requerimientos ambiguos entrevistando a los equipos usuarios para relevar objetivos concretos de latencia y volumen de datos esperado. Traducir esas necesidades en un RFC técnico con supuestos explícitos y objetivos descartados brinda claridad y destraba la implementación iterativa.",
    category: "Behavioral",
    tags: ["ambiguity", "rfc", "systems design", "requirements", "problem solving"],
    company: "MercadoLibre",
    role: "Sr Software Engineer - NoSQL Service Team",
    favorite: false,
    createdAt: 1789572000000,
  },
];

