import { MasterAnswer } from "./interviewHelpers";

/**
 * Banco Maestro VAIRIX — Senior Technical Architect
 * Alineado a la búsqueda liderada por Romina Raffo De León (IT Recruiter en VAIRIX):
 * "Senior Technical Architect con experiencia en arquitectura, TypeScript, AI/LLM/RAG y MLOps.
 * Perfil hands-on, capaz de diseñar soluciones, programar y tomar decisiones técnicas con clientes."
 *
 * Directivas estrictas:
 * - Cumplimiento del Zero-Bullet Mandate: exactamente 2 oraciones concisas y directas sin viñetas.
 * - Discriminar +8 años IT total vs ~4 años Cloud/DevOps/Arquitectura moderna.
 * - Anclado 100% al CV real de Guillermo Fernando Farfán Romero (Salta, Argentina).
 * - Bilingüe: respuestas orales fluidas en inglés y español para entrevista con Romina y clientes en EE.UU.
 */
export const VAIRIX_MASTER_ANSWERS: MasterAnswer[] = [
  // ══════════════════════════════════════════════════════════
  // SECCIÓN 1: SCREENING & FIT CULTURAL CON ROMINA RAFFO DE LEÓN
  // ══════════════════════════════════════════════════════════
  {
    id: "vairix_tell_me_about_yourself",
    question: "Tell me about yourself or walk me through your background and experience.",
    enText: "I am a Senior Technical Architect with eight years in software systems and four years specializing in cloud, Kubernetes, and GenAI architectures. I combine hands-on TypeScript and Python engineering with direct client-facing leadership for high-growth US technology teams.",
    esText: "Soy Senior Technical Architect con ocho años en sistemas de software y cuatro años especializados en cloud, Kubernetes y arquitecturas GenAI. Combino desarrollo hands-on en TypeScript y Python con liderazgo técnico directo frente a clientes de Estados Unidos.",
    category: "Screening",
    tags: ["presentation", "background", "about me", "introduction", "cv", "trayectoria"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_experience_strict",
    question: "¿Cuántos años de experiencia tienes en arquitectura de software y plataformas cloud?",
    enText: "I bring over eight years of total software engineering experience alongside four years focused specifically on cloud infrastructure, DevOps, and modern AI architectures. This foundation ensures I can both design scalable distributed systems and actively write production-grade code.",
    esText: "Cuento con más de ocho años de experiencia total en ingeniería de software y cuatro años dedicados específicamente a infraestructura cloud, DevOps y arquitecturas de IA. Esta base me permite diseñar sistemas distribuidos escalables y escribir código de producción activamente.",
    category: "Screening",
    tags: ["experience", "years", "años", "seniority"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_why_vairix",
    question: "¿Por qué te interesa sumarte a VAIRIX y este rol de Senior Technical Architect?",
    enText: "VAIRIX stands out for pairing top nearshore engineering talent with ambitious US clients solving real architectural and GenAI challenges. This Senior Architect role perfectly aligns with my passion for designing scalable systems while staying deeply hands-on in code.",
    esText: "VAIRIX se destaca por unir talento nearshore de primer nivel con clientes de Estados Unidos que resuelven desafíos reales de arquitectura y GenAI. Este rol de Senior Architect coincide exactamente con mi pasión por diseñar sistemas escalables programando activamente.",
    category: "Screening",
    tags: ["motivation", "why vairix", "role", "nearshore", "impact"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_hands_on_philosophy",
    question: "¿Cómo equilibras el rol de arquitecto técnico con ser 100% hands-on en programación?",
    enText: "I believe effective software architects must write code to keep their architectural decisions grounded and practically validated. I typically spend sixty percent of my time designing and programming core modules while dedicating the rest to client alignment.",
    esText: "Considero que los arquitectos efectivos deben programar para mantener sus decisiones de diseño fundamentadas y validadas en la práctica. Suelo dedicar el sesenta por ciento de mi tiempo a diseñar y programar módulos centrales y el resto a alinear clientes.",
    category: "Screening",
    tags: ["hands-on", "coding", "architecture balance", "programming", "practical"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_salary_expectation",
    question: "¿Cuáles son tus pretensiones salariales para este puesto contractor en VAIRIX?",
    enText: "My reference compensation is four thousand US dollars per month gross, or approximately twenty-five to thirty dollars per hour contractor. I am open to discussing the structure depending on the client scope, technical responsibilities, and overall project complexity.",
    esText: "Mi remuneración de referencia ronda los cuatro mil dólares mensuales brutos, o entre veinticinco y treinta dólares por hora contractor. Estoy abierto a evaluar la estructura según el alcance del cliente, las responsabilidades técnicas y la complejidad del proyecto.",
    category: "Screening",
    tags: ["salary", "remuneración", "expectativa", "compensación", "rate", "contractor"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_english_fluency",
    question: "How comfortable are you communicating technical decisions in English with US clients and stakeholders?",
    enText: "I communicate fluently in professional technical English across daily standups, architectural design reviews, and high-stakes client strategy sessions. My focus is articulating complex trade-offs with absolute clarity so both engineers and non-technical stakeholders stay fully aligned.",
    esText: "Me comunico con fluidez en inglés técnico profesional durante standups diarios, revisiones de arquitectura y sesiones estratégicas con clientes. Mi prioridad es articular trade-offs complejos con total claridad para mantener alineados tanto a ingenieros como a stakeholders no técnicos.",
    category: "Screening",
    tags: ["english", "communication", "clients", "stakeholders", "idioma"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_remote_work_salta",
    question: "¿Cómo gestionas el trabajo remoto y la comunicación asíncrona con equipos en diferentes husos horarios?",
    enText: "I work remotely from Salta, Argentina, using structured Architecture Decision Records and clear pull requests to keep teams asynchronously synchronized. Having dedicated high-speed fiber and an isolated home office guarantees seamless participation across all US time zones.",
    esText: "Trabajo en remoto desde Salta utilizando Architecture Decision Records estructurados y pull requests claros para mantener a los equipos sincronizados asíncronamente. Contar con fibra óptica de alta velocidad y oficina dedicada garantiza participación fluida en husos horarios de Estados Unidos.",
    category: "Screening",
    tags: ["remote", "salta", "asynchronous", "communication", "setup"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_casual_dog_luna",
    question: "¿Qué haces fuera del trabajo o en tu tiempo libre para despejarte?",
    enText: "Outside of software architecture, I spend quality time outdoors walking with my rescued dog Luna in the hills of Salta. These daily walks keep me energized and bring fresh perspectives for solving intricate distributed systems problems.",
    esText: "Fuera de la arquitectura de software, disfruto de actividades al aire libre caminando con mi perrita rescatada Luna en los cerros de Salta. Estas caminatas diarias me renuevan la energía y me aportan perspectiva para resolver problemas complejos de sistemas.",
    category: "Screening",
    tags: ["casual", "icebreaker", "hobbies", "luna", "salta", "personal"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_availability",
    question: "¿Cuál es tu disponibilidad de inicio para incorporarte a este proyecto?",
    enText: "I have immediate availability to start full-time and can integrate into client ceremonies and codebases right away. My development workstation and cloud credentials setup are completely ready for an instant, friction-free onboarding.",
    esText: "Tengo disponibilidad inmediata para comenzar full-time y puedo integrarme a las ceremonias y repositorios del cliente sin demoras. Mi entorno de desarrollo y accesos cloud están completamente listos para un onboarding ágil y sin fricciones.",
    category: "Screening",
    tags: ["availability", "start date", "disponibilidad", "onboarding"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 2: ARQUITECTURA DE SISTEMAS & ENFOQUE HANDS-ON
  // ══════════════════════════════════════════════════════════
  {
    id: "vairix_arch_approach",
    question: "How do you approach designing an enterprise cloud solution from the ground up for a new client?",
    enText: "I start by mapping core domain boundaries, latency constraints, and operational goals before selecting any specific framework or cloud provider. Then I build a working proof of concept to validate integration assumptions before rolling out infrastructure with Terraform.",
    esText: "Comienzo delimitando los contextos del dominio, restricciones de latencia y objetivos operativos antes de elegir un framework o proveedor cloud específico. Luego construyo una prueba de concepto funcional para validar supuestos antes de desplegar infraestructura con Terraform.",
    category: "Architecture",
    tags: ["system design", "cloud architecture", "poc", "methodology", "enterprise"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_arch_microservices_vs_monolith",
    question: "When do you recommend microservices versus a modular monolith for a growing client platform?",
    enText: "A modular monolith is often the best default to maintain high delivery velocity and prevent premature distributed system overhead. I only decompose services into microservices when distinct teams, independent scaling profiles, or isolated security boundaries genuinely require it.",
    esText: "Un monolito modular suele ser la mejor opción inicial para mantener velocidad de entrega y evitar la complejidad prematura de sistemas distribuidos. Solo descompongo en microservicios cuando equipos independientes, perfiles de escalabilidad dispares o aislamiento de seguridad lo justifican.",
    category: "Architecture",
    tags: ["microservices", "monolith", "modular monolith", "decomposition", "trade-offs"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_arch_adrs",
    question: "How do you document architectural decisions and maintain alignment across distributed engineering teams?",
    enText: "I establish lightweight Architecture Decision Records stored directly in git alongside the source code they govern. Each ADR captures the problem context, considered alternatives, chosen trade-offs, and downstream consequences to preserve institutional memory across team iterations.",
    esText: "Implemento Architecture Decision Records ágiles almacenados directamente en git junto al código fuente que gobiernan. Cada ADR documenta el contexto del problema, alternativas consideradas, trade-offs elegidos y consecuencias posteriores para preservar la memoria técnica del equipo.",
    category: "Architecture",
    tags: ["adrs", "documentation", "alignment", "governance", "trade-offs"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_arch_event_driven",
    question: "When do you adopt event-driven architectures and how do you ensure eventual consistency?",
    enText: "I introduce event-driven architectures when decoupling asynchronous background workflows from user-facing request cycles improves throughput and fault tolerance. I guarantee eventual consistency through idempotent consumer handlers, transactional outbox patterns, and robust dead-letter queue reprocessing.",
    esText: "Adopto arquitecturas orientadas a eventos cuando desacoplar flujos de fondo asíncronos del ciclo de respuesta mejora el throughput y la tolerancia a fallos. Garantizo consistencia eventual mediante consumidores idempotentes, patrón transactional outbox y reprocesamiento en colas de mensajes fallidos.",
    category: "Architecture",
    tags: ["event-driven", "kafka", "pubsub", "outbox", "eventual consistency", "idempotency"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_arch_resilience",
    question: "How do you design distributed systems to handle partial failures and regional outages gracefully?",
    enText: "I design systems with the fundamental assumption that downstream services and networks will experience unexpected interruptions. Implementing circuit breakers, exponential backoff with jitter, graceful degradation, and health check readiness probes keeps platforms resilient under stress.",
    esText: "Diseño sistemas asumiendo que los servicios downstream y las redes van a experimentar interrupciones inesperadas. Implementar circuit breakers, reintentos con backoff exponencial y jitter, degradación elegante y sondas de readiness mantiene la plataforma resiliente bajo estrés.",
    category: "Architecture",
    tags: ["resilience", "circuit breaker", "retries", "high availability", "fault tolerance"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_arch_database_selection",
    question: "How do you choose between relational, document, and vector databases for a modern cloud application?",
    enText: "I evaluate database selection based on query access patterns, transaction boundaries, and schema mutability requirements. PostgreSQL serves as our reliable transactional backbone with pgvector for embeddings, reserving NoSQL engines strictly for unindexed high-volume streaming payloads.",
    esText: "Evalúo la elección de base de datos según los patrones de consulta, límites transaccionales y mutabilidad del esquema. PostgreSQL actúa como base transaccional sólida con pgvector para embeddings, reservando motores NoSQL exclusivamente para streaming masivo de documentos sin relaciones.",
    category: "Architecture",
    tags: ["database selection", "postgresql", "pgvector", "nosql", "persistence"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_arch_api_design",
    question: "What are your core principles for designing enterprise-grade APIs for client applications?",
    enText: "I prioritize backward compatibility, strict request validation schemas, and explicit error contracts with predictable HTTP semantics. Adding idempotency headers for mutating calls and comprehensive OpenAPI documentation ensures smooth third-party integration without unexpected regressions.",
    esText: "Priorizo retrocompatibilidad, esquemas estrictos de validación y contratos de error explícitos con semántica HTTP predecible. Incorporar encabezados de idempotencia en mutaciones y documentación OpenAPI exhaustiva asegura integraciones externas fluidas sin regresiones inesperadas.",
    category: "Architecture",
    tags: ["api design", "rest", "idempotency", "contracts", "openapi"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_arch_technical_debt",
    question: "How do you manage and reduce technical debt while clients continue demanding new product features?",
    enText: "I allocate a predictable twenty percent capacity within each sprint to refactor critical bottlenecks alongside feature delivery. Framing technical debt reduction in terms of developer velocity, lower cloud expenses, and decreased incident risk earns client trust.",
    esText: "Asigno un veinte por ciento constante de la capacidad de cada sprint a refactorizar cuellos de botella críticos junto al desarrollo. Explicar la reducción de deuda técnica en términos de velocidad de entrega, menores costos cloud y menos incidentes genera confianza.",
    category: "Architecture",
    tags: ["technical debt", "refactoring", "velocity", "stakeholder management"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 3: TYPESCRIPT & BACKEND / FULLSTACK ARCHITECTURE
  // ══════════════════════════════════════════════════════════
  {
    id: "vairix_ts_enterprise_patterns",
    question: "How do you structure enterprise TypeScript backends to keep them scalable and maintainable?",
    enText: "I apply clean architecture principles with strict separation between business entities, use cases, and infrastructural adapters. Enabling TypeScript strict mode and isolating external dependencies behind interfaces guarantees high testability and clean domain evolution.",
    esText: "Aplico principios de arquitectura limpia separando estrictamente entidades de negocio, casos de uso y adaptadores de infraestructura. Activar el modo estricto de TypeScript y aislar dependencias externas detrás de interfaces garantiza alta testeabilidad y evolución limpia del dominio.",
    category: "TypeScript",
    tags: ["typescript", "clean architecture", "domain driven", "strict mode", "backend"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_ts_type_safety",
    question: "How do you achieve end-to-end type safety across the entire application stack from database to frontend?",
    enText: "I use Zod schemas as the single source of truth for runtime validation and static TypeScript type inference. Combining shared contract libraries with tools like tRPC or OpenAPI generators eliminates typing mismatches across distributed services.",
    esText: "Utilizo esquemas de Zod como fuente única de verdad para validación en tiempo de ejecución e inferencia de tipos estáticos. Combinar librerías de contratos compartidas con tRPC o generadores de OpenAPI elimina discrepancias de tipado entre servicios distribuidos.",
    category: "TypeScript",
    tags: ["type safety", "zod", "trpc", "contracts", "validation"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_ts_event_loop",
    question: "How do you troubleshoot Node.js event loop lag and memory leaks in production TypeScript services?",
    enText: "I capture heap snapshots and CPU profiles using Clinic.js and Node inspector to pinpoint memory leaks and blocking synchronous operations. Offloading heavy CPU tasks to worker threads keeps the event loop responsive under high concurrent load.",
    esText: "Capturo volcados de memoria y perfiles de CPU con Clinic.js e inspectores de Node para detectar pérdidas de memoria y operaciones síncronas bloqueantes. Delegar tareas de cómputo intensivo a worker threads mantiene el bucle de eventos respondiendo bajo alta concurrencia.",
    category: "TypeScript",
    tags: ["event loop", "memory leak", "profiling", "performance", "clinic js", "worker threads"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_ts_async_concurrency",
    question: "How do you handle rate-limited external APIs and background task concurrency in TypeScript?",
    enText: "I manage asynchronous concurrency using Redis-backed queues with BullMQ to enforce rate limits, retries, and backoff schedules. This prevents event loop starvation while ensuring third-party API quotas are never exceeded during traffic spikes.",
    esText: "Gestiono concurrencia asíncrona mediante colas respaldadas por Redis con BullMQ para aplicar límites de tasa, reintentos y políticas de retroceso. Esto evita saturar el event loop y asegura respetar las cuotas de APIs externas durante picos de tráfico.",
    category: "TypeScript",
    tags: ["concurrency", "bullmq", "redis", "rate limiting", "queues"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_ts_testing_strategy",
    question: "What is your testing philosophy for TypeScript microservices and how do you ensure high coverage?",
    enText: "I rely on the testing pyramid, prioritizing fast unit tests for business logic and Testcontainers for realistic database integration tests. Running Vitest in CI pipelines ensures pull requests maintain strict regression protection without slowing down development cycles.",
    esText: "Me baso en la pirámide de pruebas, priorizando tests unitarios rápidos para lógica de negocio y Testcontainers para integración realista con bases de datos. Ejecutar Vitest en CI asegura protección continua contra regresiones sin frenar los ciclos de entrega.",
    category: "TypeScript",
    tags: ["testing", "vitest", "testcontainers", "integration tests", "ci"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_ts_orm_vs_querybuilder",
    question: "Prisma, Drizzle, or raw SQL with pg-promise: what data access layer do you recommend in TypeScript?",
    enText: "Drizzle ORM offers the best balance today because it provides compile-time type safety with zero runtime query overhead. Prisma works well for rapid MVPs, but Drizzle or raw parameterized SQL scales significantly better under intensive throughput.",
    esText: "Drizzle ORM ofrece el mejor balance actual porque brinda seguridad de tipos en compilación con cero sobrecarga en tiempo de ejecución. Prisma funciona bien para MVPs rápidos, pero Drizzle o SQL parametrizado escalan notablemente mejor bajo alto throughput.",
    category: "TypeScript",
    tags: ["drizzle", "prisma", "orm", "sql", "performance"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 4: AI, LLM & RAG (RETRIEVAL-AUGMENTED GENERATION)
  // ══════════════════════════════════════════════════════════
  {
    id: "vairix_rag_architecture",
    question: "Walk me through your production RAG architecture from document ingestion to final LLM generation.",
    enText: "The pipeline ingests raw documents, applies semantic chunking, and stores generated embeddings alongside metadata in PostgreSQL with pgvector. At query time, a hybrid search retrieves top candidates, passes them to a cross-encoder reranker, and prompts the LLM.",
    esText: "El pipeline ingiere documentos, aplica particionado semántico y almacena embeddings con metadatos en PostgreSQL utilizando pgvector. En tiempo de consulta, una búsqueda híbrida recupera los mejores candidatos, los reordena con un cross-encoder y alimenta al LLM.",
    category: "AI & RAG",
    tags: ["rag", "architecture", "pipeline", "ingestion", "vector search", "reranking"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_rag_chunking",
    question: "What chunking strategy do you recommend for complex documents like manuals, policies, or contracts?",
    enText: "I use document-aware semantic chunking that splits text based on markdown headers and logical paragraphs rather than fixed character counts. Including a fifty-token sliding overlap preserves crucial contextual continuity across chunk boundaries during similarity retrieval.",
    esText: "Utilizo particionado semántico basado en la estructura del documento, dividiendo según títulos markdown y párrafos en lugar de caracteres fijos. Incluir una superposición de cincuenta tokens conserva la continuidad del contexto entre fragmentos durante la recuperación vectorial.",
    category: "AI & RAG",
    tags: ["chunking", "semantic chunking", "embeddings", "overlap", "documents"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_rag_vector_db",
    question: "Why choose PostgreSQL with pgvector over dedicated vector databases like Pinecone, Weaviate, or Milvus?",
    enText: "PostgreSQL with pgvector allows querying vector embeddings and operational business tables within a single ACID-compliant transactional boundary. This completely eliminates data synchronization drift and avoids operating yet another standalone managed vector service.",
    esText: "PostgreSQL con pgvector permite consultar embeddings vectoriales y tablas operacionales dentro del mismo límite transaccional con soporte ACID. Esto elimina por completo el desfase de sincronización y evita gestionar otro servicio vectorial independiente.",
    category: "AI & RAG",
    tags: ["pgvector", "pinecone", "vector database", "postgresql", "acid"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_rag_hybrid_search",
    question: "Why is hybrid search combining lexical BM25 and dense vector embeddings essential for production RAG?",
    enText: "Dense vector search excels at capturing conceptual semantics but frequently misses exact product identifiers, error codes, and technical jargon. Combining BM25 keyword matching with vector cosine distance using Reciprocal Rank Fusion delivers superior retrieval accuracy.",
    esText: "La búsqueda vectorial densa captura el significado conceptual pero suele fallar en códigos exactos, identificadores de producto y términos técnicos. Combinar coincidencias léxicas con similitud coseno usando Reciprocal Rank Fusion ofrece una precisión de recuperación muy superior.",
    category: "AI & RAG",
    tags: ["hybrid search", "bm25", "reciprocal rank fusion", "dense embeddings", "accuracy"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_rag_reranking",
    question: "How does a cross-encoder reranker like Cohere Rerank improve RAG answer quality and relevance?",
    enText: "Bi-encoders retrieve top candidates quickly by comparing isolated embedding vectors, but they cannot evaluate deep token-level cross-attention interactions. Applying a cross-encoder reranker over the top twenty candidates reorders the most relevant passages before prompt injection.",
    esText: "Los bi-encoders recuperan candidatos rápido comparando vectores aislados, pero no evalúan la interacción cruzada entre tokens de consulta y documento. Aplicar un modelo de reranking sobre los veinte mejores candidatos asegura inyectar los fragmentos más relevantes al prompt.",
    category: "AI & RAG",
    tags: ["reranking", "cohere", "cross-encoder", "relevance", "top-k"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_rag_hallucinations",
    question: "How do you detect and mitigate hallucinations in customer-facing generative AI applications?",
    enText: "I enforce strict system prompt guardrails mandating that the model answer exclusively using provided context passages while admitting missing knowledge. In addition, I run automated validation checks ensuring generated statements directly correlate with retrieved source citations.",
    esText: "Aplico directivas estrictas en el prompt del sistema exigiendo responder exclusivamente con el contexto provisto y declarar explícitamente cuando falta información. Además, implemento validaciones automáticas que verifican que cada afirmación generada provenga de citas de fuentes recuperadas.",
    category: "AI & RAG",
    tags: ["hallucinations", "guardrails", "grounding", "citations", "safety"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_rag_evals",
    question: "How do you evaluate and benchmark RAG pipelines systematically using frameworks like Ragas or TruLens?",
    enText: "I track faithfulness, answer relevancy, and context recall continuously across golden evaluation datasets in our automated CI/CD pipeline. Any prompt or chunking modification that lowers semantic alignment scores fails the build before deploying to production.",
    esText: "Mido fidelidad, relevancia de respuesta y cobertura de contexto continuamente sobre datasets de evaluación en nuestro pipeline de CI/CD. Cualquier cambio de prompt o particionado que reduzca los puntajes de alineación semántica detiene el despliegue a producción.",
    category: "AI & RAG",
    tags: ["evaluations", "ragas", "trulens", "benchmarking", "faithfulness"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_rag_latency_cost",
    question: "How do you optimize latency and token costs in high-volume enterprise LLM applications?",
    enText: "I implement semantic caching for frequent queries, route simpler tasks to lightweight models, and stream token responses to users immediately. This multi-tiered strategy slashes token expenditures by over forty percent while keeping perceived latency under one second.",
    esText: "Implemento caché semántico para consultas recurrentes, derivo tareas simples a modelos más livianos y transmito respuestas en streaming inmediatamente. Esta estrategia en capas reduce los costos de tokens significativamente manteniendo la latencia percibida por debajo de un segundo.",
    category: "AI & RAG",
    tags: ["latency", "costs", "token optimization", "semantic caching", "streaming"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_ai_agents",
    question: "How do you design autonomous AI agents using tool calling and structured outputs reliably?",
    enText: "I use state machines with frameworks like LangGraph to constrain agent execution flow and avoid infinite reasoning loops. Forcing tool outputs through strict Zod schemas ensures function parameters remain deterministic and safe before triggering backend mutations.",
    esText: "Utilizo máquinas de estado con herramientas como LangGraph para delimitar el flujo de los agentes y evitar bucles infinitos de razonamiento. Validar los llamados a funciones mediante esquemas estrictos de Zod asegura que los parámetros sean deterministas antes de ejecutar mutaciones.",
    category: "AI & RAG",
    tags: ["agents", "langgraph", "tool calling", "structured outputs", "state machine"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_ai_guardrails",
    question: "How do you protect production LLM services against prompt injections and sensitive data leaks?",
    enText: "I deploy pre-execution guardrails that redact personally identifiable information and detect adversarial jailbreak patterns before queries reach the LLM. Post-generation filters further inspect generated tokens to prevent confidential data exfiltration or policy violations.",
    esText: "Implemento filtros previos que anonimizan información personal identificable y detectan patrones de inyección maliciosa antes de consultar al LLM. Filtros posteriores inspeccionan los tokens generados para impedir la filtración accidental de datos confidenciales.",
    category: "AI & RAG",
    tags: ["security", "prompt injection", "guardrails", "pii", "redaction"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 5: MLOPS, DEVOPS & CLOUD INFRASTRUCTURE
  // ══════════════════════════════════════════════════════════
  {
    id: "vairix_mlops_lifecycle",
    question: "What does an end-to-end MLOps and LLMOps lifecycle look like for your production deployments?",
    enText: "The MLOps lifecycle tracks versioned prompts and evaluation datasets alongside infrastructure manifests in automated GitHub Actions pipelines. Changes must pass automated regression benchmarks and canary testing before advancing to production container clusters.",
    esText: "El ciclo de MLOps gestiona versiones de prompts y datasets de evaluación junto a manifiestos de infraestructura en GitHub Actions. Cada cambio debe superar pruebas automatizadas de regresión y despliegues canary antes de llegar a los clusters de producción.",
    category: "MLOps & Cloud",
    tags: ["mlops", "llmops", "lifecycle", "versioning", "canary"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_mlops_observability",
    question: "How do you monitor and trace LLM applications in production to ensure performance and cost control?",
    enText: "I integrate OpenTelemetry and dedicated LLM tracing tools like Langfuse to record latency percentiles, token usage, and retrieval steps. Setting up automated threshold alerts notifies on-call teams before token cost spikes or elevated error rates impact clients.",
    esText: "Integro OpenTelemetry y herramientas de trazabilidad como Langfuse para registrar percentiles de latencia, consumo de tokens y pasos de búsqueda. Configurar alertas automáticas por umbrales notifica al equipo de guardia antes de que desvíos de costo afecten al cliente.",
    category: "MLOps & Cloud",
    tags: ["observability", "langfuse", "opentelemetry", "tracing", "monitoring"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_devops_containers",
    question: "When do you choose Kubernetes over managed container services like Google Cloud Run or AWS Fargate?",
    enText: "Cloud Run and Fargate are ideal for serverless microservices with variable traffic patterns that benefit from zero infrastructure maintenance. I reserve Kubernetes for complex architectures needing granular networking, sidecar service meshes, or persistent distributed state.",
    esText: "Cloud Run y Fargate son ideales para microservicios con tráfico variable que se benefician de no requerir administración de servidores. Reservo Kubernetes para arquitecturas complejas que exigen control fino de red, mallas de servicios o estado distribuido persistente.",
    category: "MLOps & Cloud",
    tags: ["kubernetes", "cloud run", "fargate", "containers", "serverless"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_devops_terraform",
    question: "How do you structure Terraform code to keep multi-environment cloud infrastructure reliable and DRY?",
    enText: "I organize Terraform configurations into modular, reusable components with remote state locking and separate workspace state files per environment. Automated validation checks in CI enforce security compliance and prevent unintended state drift prior to applying changes.",
    esText: "Organizo las configuraciones de Terraform en módulos reutilizables con bloqueo de estado remoto y archivos de estado separados por entorno. Validaciones automáticas en CI aplican reglas de seguridad e impiden desvíos de configuración antes de aplicar cambios.",
    category: "MLOps & Cloud",
    tags: ["terraform", "iac", "modules", "state management", "drift"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_devops_cicd",
    question: "How do you design CI/CD pipelines to ensure zero-downtime releases and rapid rollbacks?",
    enText: "I build pipelines that generate immutable container images, run comprehensive test suites, and execute blue-green or rolling updates automatically. Linking readiness probes with automated health metrics triggers instant rollbacks if error rates exceed baseline tolerances.",
    esText: "Diseño pipelines que generan imágenes inmutables de contenedores, ejecutan suites completas de pruebas y aplican despliegues blue-green automáticamente. Vincular sondas de readiness con métricas de salud activa rollbacks inmediatos si las tasas de error superan lo tolerado.",
    category: "MLOps & Cloud",
    tags: ["ci/cd", "blue-green", "rolling update", "rollback", "deployments"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_devops_secrets",
    question: "How do you manage secrets and enforce least-privilege IAM security across cloud environments?",
    enText: "I inject credentials dynamically from managed secret managers into runtime memory without ever committing environment files to git repositories. IAM service accounts are granted strictly scoped roles, avoiding wildcard permissions and rotating keys on schedule.",
    esText: "Inyecto credenciales dinámicamente desde gestores de secretos a la memoria del proceso sin commitear archivos de variables de entorno al repositorio. Las cuentas de servicio reciben permisos estrictamente acotados, evitando comodines y rotando credenciales periódicamente.",
    category: "MLOps & Cloud",
    tags: ["secrets", "iam", "least privilege", "security", "credentials"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 6: CLIENT-FACING DECISION MAKING & LEADERSHIP
  // ══════════════════════════════════════════════════════════
  {
    id: "vairix_client_communication",
    question: "How do you communicate technical architectural trade-offs to non-technical US clients and executives?",
    enText: "I translate architectural decisions into tangible business outcomes such as monthly infrastructure costs, development velocity, and system reliability metrics. Presenting clear options with their respective trade-offs empowers stakeholders to make confident, well-informed strategic decisions.",
    esText: "Traduzco decisiones de arquitectura en resultados de negocio tangibles como costos operativos mensuales, velocidad de desarrollo y métricas de confiabilidad. Presentar opciones claras con sus trade-offs permite a los stakeholders tomar decisiones estratégicas fundamentadas.",
    category: "Leadership & Clients",
    tags: ["client communication", "trade-offs", "stakeholders", "business alignment"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_client_pushback",
    question: "How do you handle a client who insists on using unnecessary complexity or an unproven buzzword technology?",
    enText: "I acknowledge their business motivation first and then present comparative data illustrating maintenance overhead, cost implications, and delivery delays. I usually propose a lightweight proof of concept that tests the technology safely without endangering the main roadmap.",
    esText: "Comprendo primero la motivación del cliente y presento datos comparativos sobre costos de mantenimiento, impacto presupuestario y demoras de entrega. Suelo proponer una prueba de concepto acotada para validar la tecnología de forma segura sin comprometer el roadmap principal.",
    category: "Leadership & Clients",
    tags: ["pushback", "yagni", "client management", "pragmatism"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_client_scope_creep",
    question: "How do you manage scope creep and changing technical requirements mid-sprint with a client?",
    enText: "I maintain transparent communication by explaining how new requirements impact current sprint deliverables and production launch timelines. We collaborate to prioritize incoming features against the backlog, swapping lower-priority items to maintain realistic delivery commitments.",
    esText: "Mantengo comunicación transparente explicando cómo los nuevos requerimientos impactan las entregas del sprint y los plazos de salida a producción. Colaboramos para priorizar los cambios en el backlog, intercambiando tareas secundarias para sostener compromisos realistas.",
    category: "Leadership & Clients",
    tags: ["scope creep", "backlog", "sprint management", "transparency"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_lead_mentoring",
    question: "How do you mentor mid-level and senior engineers on your team while driving architectural standards?",
    enText: "I mentor engineers through collaborative design pairing, constructive code reviews, and explaining the architectural rationale behind design patterns. Empowering team members to author their own decision proposals fosters technical ownership and accelerates team growth.",
    esText: "Acompaño a los ingenieros mediante sesiones colaborativas de diseño, revisiones constructivas de código y explicando el fundamento de cada patrón de arquitectura. Fomentar que propongan sus propias soluciones fortalece el ownership técnico y acelera el crecimiento del equipo.",
    category: "Leadership & Clients",
    tags: ["mentoring", "leadership", "code reviews", "empowerment"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_lead_code_reviews",
    question: "What is your philosophy and standard for conducting code and architecture reviews?",
    enText: "I focus reviews on architectural alignment, error handling, performance implications, and readability rather than subjective stylistic preferences. Automated linters enforce style conventions, allowing humans to concentrate on domain accuracy and security boundaries.",
    esText: "Foco las revisiones en alineación de arquitectura, manejo de errores, rendimiento y legibilidad en lugar de preferencias de estilo subjetivas. Los linters automatizados cuidan el formato, permitiendo a los revisores concentrarse en la lógica del dominio y la seguridad.",
    category: "Leadership & Clients",
    tags: ["code reviews", "standards", "architecture reviews", "linters"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_lead_disagreements",
    question: "How do you resolve strong technical disagreements among senior engineers on architecture choices?",
    enText: "I redirect debates away from personal opinion by establishing objective evaluation criteria based on performance, operational cost, and delivery risk. If consensus remains split, we build short time-boxed prototypes and let empirical benchmark results settle the direction.",
    esText: "Canalizo los debates lejos de opiniones personales definiendo criterios objetivos de evaluación basados en rendimiento, costo operativo y riesgo de entrega. Si persiste la discrepancia, construimos prototipos rápidos y dejamos que los benchmarks resuelvan la decisión.",
    category: "Leadership & Clients",
    tags: ["conflict resolution", "disagreements", "consensus", "benchmarks"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_client_culture_fit",
    question: "How do you adapt to fast-paced US startup culture and shifting business priorities?",
    enText: "I thrive in fast-paced environments by building modular systems that accommodate change without requiring destructive ground-up rewrites. Combining proactive communication with rapid, incremental releases allows the team to pivot smoothly alongside market opportunities.",
    esText: "Me adapto con naturalidad a entornos dinámicos diseñando sistemas modulares que asimilan cambios sin requerir reescrituras completas. Combinar comunicación proactiva con entregas incrementales frecuentes permite al equipo pivotar con agilidad según las necesidades del mercado.",
    category: "Leadership & Clients",
    tags: ["culture fit", "startups", "agility", "us culture"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 7: HISTORIAS STAR & EXPERIENCIAS REALES
  // ══════════════════════════════════════════════════════════
  {
    id: "vairix_star_rag_optimization",
    question: "Describe a situation where you built or optimized a RAG pipeline facing accuracy or latency challenges.",
    enText: "Our initial vector search returned inaccurate results for specialized domain queries, causing unacceptable hallucination rates in customer conversations. I implemented hybrid BM25 and pgvector retrieval with Cohere reranking, boosting retrieval precision while cutting hallucinations dramatically.",
    esText: "Nuestra búsqueda vectorial inicial devolvía resultados imprecisos en consultas de dominio técnico, generando alucinaciones en respuestas a usuarios. Implementé recuperación híbrida con BM25 y pgvector junto a reranking de Cohere, aumentando la precisión y reduciendo alucinaciones notablemente.",
    category: "STAR Stories",
    tags: ["star", "rag", "hybrid search", "pgvector", "optimization", "accuracy"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_star_cloud_migration",
    question: "Tell me about a major cloud architecture or platform migration you led successfully.",
    enText: "A legacy monolith was struggling with unpredictable deployment downtime and runaway infrastructure expenses under growing user traffic. I architected a containerized deployment on Kubernetes using Terraform and automated CI/CD pipelines, achieving zero-downtime releases and reducing operational overhead.",
    esText: "Un monolito legacy sufría caídas durante los despliegues y costos elevados de infraestructura ante el crecimiento de usuarios. Diseñé una arquitectura de contenedores sobre Kubernetes con Terraform y pipelines automatizados, logrando despliegues continuos sin interrupción y reduciendo gastos operativos.",
    category: "STAR Stories",
    tags: ["star", "migration", "kubernetes", "terraform", "ci/cd", "cost reduction"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_star_production_incident",
    question: "Tell me about a critical production incident or bottleneck you investigated and resolved.",
    enText: "A high-concurrency event caused severe database connection pool exhaustion, resulting in elevated response times and API timeout errors. I diagnosed the bottleneck, introduced PgBouncer for efficient pooling, and added Redis caching, stabilizing latencies under peak traffic.",
    esText: "Un pico de alta concurrencia agotó el pool de conexiones de base de datos, provocando demoras y timeouts en las APIs. Diagnostiqué el cuello de botella, incorporé PgBouncer para optimizar el pooling y caché en Redis, estabilizando las latencias en picos de demanda.",
    category: "STAR Stories",
    tags: ["star", "incident", "database", "pgbouncer", "redis", "troubleshooting"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_star_legacy_refactoring",
    question: "Tell me about a time you modernized a legacy codebase into modern TypeScript without disrupting production.",
    enText: "Our legacy JavaScript backend suffered from frequent runtime type exceptions and difficult onboarding due to missing interface contracts. I introduced TypeScript gradually with strict boundary types, converting core services file-by-file while maintaining full continuous integration test coverage.",
    esText: "Nuestro backend en JavaScript legacy sufría errores de tipo en runtime y onboarding complejo por falta de contratos claros. Introduje TypeScript gradualmente con tipado estricto en límites, convirtiendo módulos archivo por archivo mientras manteníamos cobertura total en integración continua.",
    category: "STAR Stories",
    tags: ["star", "modernization", "typescript", "refactoring", "technical debt"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_star_client_alignment",
    question: "Tell me about a time you had to align a client on a difficult technical trade-off.",
    enText: "A client requested a complex multi-cloud distributed database architecture that would have delayed launch dates and tripled maintenance costs. I presented a focused comparative study advocating for a resilient single-region architecture, saving months of unnecessary engineering effort.",
    esText: "Un cliente solicitó una arquitectura distribuida multi-cloud compleja que habría demorado el lanzamiento y triplicado costos operativos. Presenté un análisis comparativo fundamentando una arquitectura resiliente mono-región, ahorrando meses de esfuerzo innecesario de desarrollo.",
    category: "STAR Stories",
    tags: ["star", "client alignment", "trade-offs", "negotiation", "architecture"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },

  // ══════════════════════════════════════════════════════════
  // SECCIÓN 8: PREGUNTAS INTELIGENTES PARA ROMINA Y VAIRIX
  // ══════════════════════════════════════════════════════════
  {
    id: "vairix_q_client_details",
    question: "¿Qué me puedes contar sobre el cliente en Estados Unidos, su industria y la etapa actual del producto?",
    enText: "Could you share more details about the US client, their business domain, and where this product currently stands in its lifecycle? Understanding whether this involves zero-to-one design or scaling an existing platform helps me tailor my technical contributions.",
    esText: "¿Podrías compartirme más detalles sobre el cliente de Estados Unidos, su industria y en qué etapa se encuentra el producto actualmente? Entender si se trata de un desarrollo de cero a uno o escalar una plataforma existente me ayuda a enfocar mi aporte.",
    category: "Questions to Ask",
    tags: ["questions", "client", "product stage", "reverse questions"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_q_architect_autonomy",
    question: "¿Cuál es el nivel de autonomía del Technical Architect para definir la arquitectura con el cliente?",
    enText: "What degree of architectural autonomy will I have when collaborating with the client's engineering leadership on technology decisions? I enjoy driving pragmatic choices that balance long-term system maintainability with immediate business delivery goals.",
    esText: "¿Qué nivel de autonomía técnica tiene el arquitecto al consensuar decisiones con el liderazgo técnico del cliente? Me entusiasma impulsar decisiones pragmáticas que equilibren la mantenibilidad del sistema con los objetivos comerciales de entrega.",
    category: "Questions to Ask",
    tags: ["questions", "autonomy", "decision making", "leadership"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_q_team_composition",
    question: "¿Cómo está conformado el equipo de desarrollo entre ingenieros de VAIRIX y el equipo interno del cliente?",
    enText: "How is the engineering pod structured between VAIRIX engineers and the client's internal team members? I would love to know more about the daily agile dynamics, time zone overlap, and code collaboration workflows.",
    esText: "¿Cómo está conformado el pod de ingeniería entre los desarrolladores de VAIRIX y el equipo interno del cliente? Me interesa conocer la dinámica ágil del día a día, la superposición horaria y los flujos de colaboración en el código.",
    category: "Questions to Ask",
    tags: ["questions", "team", "structure", "collaboration", "agile"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: false,
    createdAt: 1789600000000,
  },
  {
    id: "vairix_q_next_steps",
    question: "¿Cuáles son los próximos pasos del proceso de selección después de esta conversación inicial?",
    enText: "What are the subsequent steps in the interview process following this initial screening conversation with you, Romina? I am eager to meet the technical team and dive into the deeper architectural challenges ahead.",
    esText: "¿Cuáles son los siguientes pasos del proceso de selección luego de esta conversación inicial contigo, Romina? Tengo mucho entusiasmo por conocer al equipo técnico y profundizar en los desafíos de arquitectura del proyecto.",
    category: "Questions to Ask",
    tags: ["questions", "next steps", "process", "recruiter", "romina"],
    company: "VAIRIX",
    role: "Senior Technical Architect",
    favorite: true,
    createdAt: 1789600000000,
  },
];
